# name: Build app and deploy to NPM & Sync Code To Gitee
# on:
#   #监听push操作
#   push:
#     branches:
#       # master分支，你也可以改成其他分支
#       - master
# jobs:
#   Sync-Code-To-Gitee-job:
#     # runs-on 指定job任务运行所需要的虚拟机环境
#     runs-on: ubuntu-latest
#     steps:
#       # 同步代码到 gitee
#     - name: Sync Github Repos To Gitee  # 名字随便起
#       uses: Yikun/hub-mirror-action@v1.1  # 使用Yikun/hub-mirror-action
#       with:
#         src: github/Daudxu
#         dst: gitee/coding-365
#         dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}  # SSH密钥对中的私钥
#         dst_token:  ${{ secrets.GITEE_TOKEN }}  # Gitee账户的私人令牌
#         account_type: user  # 账户类型
#         clone_style: "https"  # 使用https方式进行clone，也可以使用ssh
#         debug: true  # 启用后会显示所有执行命令
#         force_update: true  # 启用后，强制同步，即强制覆盖目的端仓库
#         static_list: 'nft-lands-tile-map-vue-component'  # 静态同步列表，在此填写需要同步的仓库名称，可填写多个
#         timeout: '600s'  # git超时设置，超时后会自动重试git操作
